#!/bin/sh

BASE="$(dirname "$0")/.."
cd "$BASE"

# Export the environment variables:
export ttiUsername="admin"
export ttiPassword="password"
export TTI_PLAYCOOKIE=$ttiUsername
export TTI_GAMESERVER="192.168.178.100"

echo "==============================="
echo "Starting Toontown Online..."
echo "Username: $ttiUsername"
echo "Gameserver: $TTI_GAMESERVER"
echo "==============================="

"../bin/python" -m toontown.toonbase.ClientStart
